name: tpiadev
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^1.1.0
  firebase_auth: ^4.14.0
  firebase_core: ^2.22.0
  firebase_ui_auth: ^1.10.0
  cloud_firestore: ^4.0.1
  image: ^3.0.1
  flutter_image: ^4.1.10
  image_picker: ^0.8.4
  flutter:
    sdk: flutter
  path_provider: ^2.0.15
  validators: ^3.0.0
  tflite_v2: ^1.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  
  assets:
   - assets/labels.txt
   - assets/model_unquant.tflite
 
  uses-material-design: true
 
