// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_w2M68U3gMigl2zXlj-s37GBHw2D8RRs',
    appId: '1:104273612721:web:15a8d6bfa8b97799a87790',
    messagingSenderId: '104273612721',
    projectId: 'tpia-d9461',
    authDomain: 'tpia-d9461.firebaseapp.com',
    storageBucket: 'tpia-d9461.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY5RBELoW9GESyLjqresiHoQnv8nUG7c4',
    appId: '1:104273612721:android:8757d919b254cf13a87790',
    messagingSenderId: '104273612721',
    projectId: 'tpia-d9461',
    storageBucket: 'tpia-d9461.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD05H6JlV419HyzCpLhr6lbLhWCNt0c-wo',
    appId: '1:104273612721:ios:21256685e9f62de6a87790',
    messagingSenderId: '104273612721',
    projectId: 'tpia-d9461',
    storageBucket: 'tpia-d9461.appspot.com',
    iosBundleId: 'com.example.tpiadev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD05H6JlV419HyzCpLhr6lbLhWCNt0c-wo',
    appId: '1:104273612721:ios:393067405d6bcdd7a87790',
    messagingSenderId: '104273612721',
    projectId: 'tpia-d9461',
    storageBucket: 'tpia-d9461.appspot.com',
    iosBundleId: 'com.example.tpiadev.RunnerTests',
  );
}
